import type { LucideIcon } from "lucide-react";
import {
  Apple,
  ArrowDownLeft,
  Baby,
  Banknote,
  Bike,
  BookOpen,
  Briefcase,
  Bus,
  Car,
  Cat,
  CircleDollarSign,
  Coffee,
  Coins,
  Dog,
  Dumbbell,
  Film,
  Flower2,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  HeartPulse,
  House,
  IceCreamCone,
  Landmark,
  Laptop,
  Lightbulb,
  MonitorSmartphone,
  MoonStar,
  Music4,
  PartyPopper,
  ParkingCircle,
  PawPrint,
  Phone,
  PiggyBank,
  Pill,
  Pizza,
  Receipt,
  Salad,
  Sandwich,
  Scissors,
  Shield,
  Shirt,
  ShoppingBasket,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Stethoscope,
  Store,
  Sun,
  Tag,
  Ticket,
  Train,
  Trees,
  Tv,
  UtensilsCrossed,
  Wallet,
  Wifi,
  Wrench
} from "lucide-react";

const iconRegistry = {
  apple: Apple,
  "arrow-down-left": ArrowDownLeft,
  baby: Baby,
  banknote: Banknote,
  bike: Bike,
  "book-open": BookOpen,
  briefcase: Briefcase,
  bus: Bus,
  car: Car,
  cat: Cat,
  "circle-dollar-sign": CircleDollarSign,
  coffee: Coffee,
  coins: Coins,
  dog: Dog,
  dumbbell: Dumbbell,
  film: Film,
  flower: Flower2,
  fuel: Fuel,
  gamepad: Gamepad2,
  gift: Gift,
  graduation: GraduationCap,
  "heart-pulse": HeartPulse,
  house: House,
  "ice-cream": IceCreamCone,
  landmark: Landmark,
  laptop: Laptop,
  lightbulb: Lightbulb,
  "monitor-smartphone": MonitorSmartphone,
  "moon-star": MoonStar,
  music: Music4,
  party: PartyPopper,
  parking: ParkingCircle,
  paw: PawPrint,
  phone: Phone,
  "piggy-bank": PiggyBank,
  pill: Pill,
  pizza: Pizza,
  receipt: Receipt,
  salad: Salad,
  sandwich: Sandwich,
  scissors: Scissors,
  shield: Shield,
  shirt: Shirt,
  "shopping-basket": ShoppingBasket,
  "shopping-cart": ShoppingCart,
  smartphone: Smartphone,
  sparkles: Sparkles,
  stethoscope: Stethoscope,
  store: Store,
  sun: Sun,
  tag: Tag,
  ticket: Ticket,
  train: Train,
  trees: Trees,
  tv: Tv,
  utensils: UtensilsCrossed,
  wallet: Wallet,
  wifi: Wifi,
  wrench: Wrench
} satisfies Record<string, LucideIcon>;

export const CATEGORY_ICON_OPTIONS = [
  { value: "tag", label: "General" },
  { value: "shopping-basket", label: "Supermercado" },
  { value: "shopping-cart", label: "Compras" },
  { value: "house", label: "Casa" },
  { value: "utensils", label: "Comida" },
  { value: "coffee", label: "Cafe" },
  { value: "pizza", label: "Pizza" },
  { value: "sandwich", label: "Snack" },
  { value: "salad", label: "Saludable" },
  { value: "ice-cream", label: "Postres" },
  { value: "apple", label: "Fruta" },
  { value: "car", label: "Coche" },
  { value: "fuel", label: "Gasolina" },
  { value: "parking", label: "Parking" },
  { value: "train", label: "Tren" },
  { value: "bus", label: "Bus" },
  { value: "bike", label: "Bici" },
  { value: "wallet", label: "Cartera" },
  { value: "banknote", label: "Billetes" },
  { value: "coins", label: "Monedas" },
  { value: "piggy-bank", label: "Ahorro" },
  { value: "receipt", label: "Recibos" },
  { value: "circle-dollar-sign", label: "Cobros" },
  { value: "arrow-down-left", label: "Transferencia" },
  { value: "landmark", label: "Banco" },
  { value: "briefcase", label: "Trabajo" },
  { value: "graduation", label: "Estudios" },
  { value: "book-open", label: "Libros" },
  { value: "laptop", label: "Portatil" },
  { value: "monitor-smartphone", label: "Tecnologia" },
  { value: "smartphone", label: "Movil" },
  { value: "phone", label: "Telefono" },
  { value: "wifi", label: "Internet" },
  { value: "tv", label: "TV" },
  { value: "film", label: "Cine" },
  { value: "music", label: "Musica" },
  { value: "gamepad", label: "Videojuegos" },
  { value: "party", label: "Fiesta" },
  { value: "ticket", label: "Entradas" },
  { value: "sparkles", label: "Caprichos" },
  { value: "gift", label: "Regalos" },
  { value: "heart-pulse", label: "Salud" },
  { value: "stethoscope", label: "Medico" },
  { value: "pill", label: "Farmacia" },
  { value: "dumbbell", label: "Gimnasio" },
  { value: "shirt", label: "Ropa" },
  { value: "scissors", label: "Peluqueria" },
  { value: "lightbulb", label: "Luz" },
  { value: "wrench", label: "Reparaciones" },
  { value: "shield", label: "Seguros" },
  { value: "baby", label: "Bebe" },
  { value: "dog", label: "Perro" },
  { value: "cat", label: "Gato" },
  { value: "paw", label: "Mascotas" },
  { value: "flower", label: "Flores" },
  { value: "trees", label: "Naturaleza" },
  { value: "sun", label: "Vacaciones" },
  { value: "moon-star", label: "Noche" },
  { value: "store", label: "Tienda" }
] as const;

export function getCategoryIcon(iconName?: string | null) {
  if (!iconName) {
    return Tag;
  }

  return iconRegistry[iconName as keyof typeof iconRegistry] ?? Tag;
}

